projeto_v12/projeto_v0/Models/Atividade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace projeto_v0.Models
{
    public class Atividade
    {
        public int id { get; set; }
        public String nome { get; set; }
        public String data_ini { get; set; }
        public String data_fim { get; set; }
        public String carga_horaria { get; set; }
        public String resumo { get; set; }
        public int cod_responsavel { get; set; }
        public String ano { get; set; }        
        public String local { get; set; }
        public int cod_tipo_ativ { get; set; }
    }
}

projeto_v12/projeto_v0/Controllers/AtividadeController.cs
using projeto_v0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace projeto_v0.Controllers
{
    public class AtividadeController : Controller    {

        AtividadeDAO atividadeDAO = new AtividadeDAO();
        public static List<Atividade> listaAtividade = new List<Atividade>();
        // GET: Atividade
        public ActionResult Index()
        {
            listaAtividade = atividadeDAO.List();
            return View(listaAtividade);
            
        }

        // GET: Atividade/Create
        public ActionResult Create()
        {
            return View();            
        }
        // POST: Atividade/Create
        [HttpPost]
        public ActionResult Create(Atividade atividade)
        {
            try
            {

                listaAtividade.Add(atividade);
                atividadeDAO.Create(atividade);
                //return RedirectToAction("Index");
                if (atividade == null) throw new Exception();
                return RedirectToAction("Index").Mensagem("Atividade registrada com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();                
                return View().Mensagem("Erro ao registrar Atividade!", "Erro");

            }
        }

        // GET: Atividade/Edit/5
        public ActionResult Edit(int id)
        {
            var atividade = listaAtividade.Single(p => p.id == id);

            return View(atividade);
        }

        // POST: Atividade/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var atividade = listaAtividade.Single(p => p.id == id);
                if (TryUpdateModel(atividade))
                {
                    atividadeDAO.Edit(atividade);
                    return RedirectToAction("Index");

                }
                //return View(atividade);
                return View().Mensagem("Atividade alterada com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao alterar atividade!", "Erro");
            }
        }

        // GET: Atividade/Delete/5
        public ActionResult Delete(int id)
        {
            Console.WriteLine("Usuario: " + id);
            var atividade = listaAtividade.Single(p => p.id == id);
            return View(atividade);
        }

        // POST: Atividade/Delete/5
        [HttpPost]
        //        public ActionResult Delete(int id, FormCollection collection)
        public ActionResult Delete(Atividade atividade)
        {
            try
            {
                listaAtividade.Remove(atividade);
                atividadeDAO.Delete(atividade);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Atividade excluído com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao excluir atividade!", "Erro");
            }
        }
        public ActionResult Detalhes(int id)
        {
            ViewBag.id=id;
            return View();
        }
    }
}

projeto_v12/projeto_v0/Controllers/CertificadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projeto_v0.Models;
using System.IO;
using Excel;
using System.Data;

namespace projeto_v0.Controllers
{
    public class CertificadoController : Controller
    {
        CertificadoDAO certificadoDAO = new CertificadoDAO();

        ParticipanteDAO participanteDAO = new ParticipanteDAO();
        public static List<Certificado> listaCertificado = new List<Certificado>();
        public static List<CertificadoParticipante> listaCertificadoPDF = new List<CertificadoParticipante>();
        public static List<Participante> listaParticipante = new List<Participante>();
        // GET: Certificado
        public ActionResult Index()
        {
            listaCertificado = certificadoDAO.List();
            return View(listaCertificado);
        }
        public ActionResult CreatePorArquivo(int? id)
        {
            ViewBag.ativ=id;
            return View();
        }

        // GET: Certificado/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Certificado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Certificado/Create
        [HttpPost]
        public ActionResult Create(Certificado Certificado)
        {
            try
            {
                // TODO: Add insert logic here
                listaCertificado.Add(Certificado);
                certificadoDAO.Create(Certificado);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Certificado registrado com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao registrar Certificado!", "Erro");

            }
        }

        // GET: Certificado/Edit/5
        public ActionResult Edit(int id)
        {

            var Certificado = listaCertificado.Single(p => p.id == id);

            return View(Certificado);
        }

        // POST: Certificado/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var Certificado = listaCertificado.Single(p => p.id == id);
                if (TryUpdateModel(Certificado))
                {
                    certificadoDAO.Edit(Certificado);
                    //return RedirectToAction("Index");
                    return RedirectToAction("Index").Mensagem("Certificado alterado com sucesso!", "Sucesso");

                }
                return View(Certificado);

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao alterar certificado!", "Erro");

            }
        }

        // GET: Certificado/Delete/5
        public ActionResult Delete(int id)
        {
            var Certificado = listaCertificado.Single(p => p.id == id);
            return View(Certificado);
        }

        // POST: Certificado/Delete/5
        [HttpPost]
        public ActionResult Delete(Certificado Certificado)
        {
            try
            {
                listaCertificado.Remove(Certificado);
                certificadoDAO.Delete(Certificado);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Certificado excluído com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao excluir certificado!", "Erro");
            }
        }
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MatriculaAlunos(HttpPostedFileBase uploadfile, Certificado Certificado)
        {


            System.Diagnostics.Debug.WriteLine("This will be displayed in output window" + Certificado.cod_atividade.ToString());
            Participante part = new Participante();
            Certificado cert = new Certificado();
            if (ModelState.IsValid)
            {
                if (uploadfile != null && uploadfile.ContentLength > 0)
                {
                    //ExcelDataReader works on binary excel file
                    Stream stream = uploadfile.InputStream;
                    //We need to written the Interface.
                    IExcelDataReader reader = null;
                    if (uploadfile.FileName.EndsWith(".xls"))
                    {
                        //reads the excel file with .xls extension
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (uploadfile.FileName.EndsWith(".xlsx"))
                    {
                        //reads excel file with .xlsx extension
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else
                    {
                        //Shows error if uploaded file is not Excel file
                        ModelState.AddModelError("File", "This file format is not supported");
                        // return View();
                    }
                    //treats the first row of excel file as Coluymn Names
                    reader.IsFirstRowAsColumnNames = true;
                    //Adding reader data to DataSet()
                    DataSet result = reader.AsDataSet();
                    reader.Close();


                    foreach (DataRow row in result.Tables[0].Rows)
                    {
                        foreach (DataColumn column in result.Tables[0].Columns)
                        {
                            if (column.ColumnName.ToString() == "Nome")
                                part.nome = row[column.ColumnName].ToString();
                            else if (column.ColumnName.ToString() == "E-mail")
                                part.email = row[column.ColumnName].ToString();
                            else if (column.ColumnName.ToString() == "CPF")
                                part.cpf = row[column.ColumnName].ToString();
                        }

                        string cpfEncontrado =participanteDAO.BuscaCPF(part.cpf);
                        if (cpfEncontrado == "")
                            cert.cod_participante = Convert.ToInt16(participanteDAO.Create(part));
                        else
                            cert.cod_participante = Convert.ToInt16(cpfEncontrado);

                        cert.cod_atividade = Certificado.cod_atividade;
                        var verificaCert = certificadoDAO.BuscaCertificadoExistente(cert.cod_atividade, cert.cod_participante);
                        if(verificaCert==0)
                            certificadoDAO.Create(cert);  
                    }
                    //Sending result data to View

                }
            }
            else
            {
                ModelState.AddModelError("File", "Please upload your file");
            }
            return RedirectToAction("Index");
        }

        public ActionResult ConcluirAtividade(int id)
        {
            listaCertificado=certificadoDAO.List(id);
            ViewBag.id = id;

            return View();
        }

        [HttpPost]
        public ActionResult ConcluirAtividade(int id, FormCollection collection)
        {
            try
            {
                
                System.Diagnostics.Debug.WriteLine("Concluir" +id+" "+collection.Get(3));
                Certificado certificado = new Certificado();
                certificado.data_emissao = collection.Get(3);
                certificado.cod_template = Convert.ToInt32(collection.Get(4));
                certificado.cod_atividade = Convert.ToInt32(id);
                certificado.cod_assinatura_1 = Convert.ToInt32(collection.Get(5));
                certificado.cod_assinatura_2 = Convert.ToInt32(collection.Get(6));
                var data = certificado.data_emissao.Split('/');
                listaParticipante = participanteDAO.ListAlunosAtividade(Convert.ToInt32(id));
                for (int i = 0; i < listaParticipante.Count(); i++)
                {
                    certificado.cod_unico_certif = data[2] + certificado.cod_atividade + certificado.cod_participante;
                    certificado.cod_participante = listaParticipante[i].id;
                    certificadoDAO.CompletarCert(certificado);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult AlunosMatriculados(int? id,int? tipo)
        {
            ViewBag.idCert = id;

            ViewBag.tipo = tipo;
            System.Diagnostics.Debug.WriteLine("ID: " + id.ToString());
            listaParticipante = participanteDAO.ListAlunosAtividade(Convert.ToInt16(id));
            
            return PartialView(listaParticipante);
        }
        
        public ActionResult CertificadoCancelado(int part,int? ativ,int? tipo)
        {
            try
            {
                var participante = listaParticipante.Single(p => p.id == part);
                listaParticipante.Remove(participante);
                certificadoDAO.DeleteCertificadoIndeferido(Convert.ToInt16(ativ), part);
                if(tipo==2)
                    return RedirectToAction("Detalhes","Atividade", new { id = Convert.ToInt32(ativ) });
                else
                    return RedirectToAction("ConcluirAtividade",new {id=Convert.ToInt32(ativ) });
            }
            catch(Exception ex)
            {
                return View();                

            }
        }
        public ActionResult CertificadoPDF(int id)
        {
            listaCertificadoPDF = certificadoDAO.ListCertificadoPDF(id);

projeto_v12/projeto_v0/Views/Atividade/Create.cshtml
@model projeto_v0.Models.Atividade

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Adicionar nova atividade</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atividade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group"> 
            <label class="control-label col-md-2">Id</label>
            <div class="col-md-10">               
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"> 
            <label class="control-label col-md-2">Nome</label>
            <div class="col-md-10">              
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Resumo</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.resumo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.resumo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">   
            <label class="control-label col-md-2">Data de Início</label>
            <div class="col-md-10">               
                @Html.EditorFor(model => model.data_ini, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_ini, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">  
            <label class="control-label col-md-2">Data de fim</label>
            <div class="col-md-10">               
                @Html.EditorFor(model => model.data_fim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_fim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Carga horária</label>
            <div class="col-md-10">               
                @Html.EditorFor(model => model.carga_horaria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carga_horaria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">  
            <label class="control-label col-md-2">Código do Responsável</label>
            <div class="col-md-10">                
                @Html.EditorFor(model => model.cod_responsavel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cod_responsavel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"> 
            <label class="control-label col-md-2">Ano</label>
            <div class="col-md-10">              
                @Html.EditorFor(model => model.ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"> 
            <label class="control-label col-md-2">Local</label>
            <div class="col-md-10">               
                @Html.EditorFor(model => model.local, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.local, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"> 
            <label class="control-label col-md-2">Código do tipo da atividade</label>
            <div class="col-md-10">                
                @Html.EditorFor(model => model.cod_tipo_ativ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cod_tipo_ativ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

projeto_v12/projeto_v0/Views/Atividade/Delete.cshtml
@model projeto_v0.Models.Atividade

@{
    ViewBag.Title = "Deelete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deletar atividade</h2>

<h3>Você tem certeza que deseja deletar essa atividade?</h3>
<div>
    <h4>Atividade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resumo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resumo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_ini)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_ini)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_fim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_fim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.carga_horaria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carga_horaria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cod_responsavel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cod_responsavel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.local)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.local)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cod_tipo_ativ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cod_tipo_ativ)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

projeto_v12/projeto_v0/Views/Atividade/Detalhes.cshtml
@model projeto_v0.Models.Participante

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Action("AlunosMatriculados", "Certificado", new { id = ViewBag.id,tipo=2 })

projeto_v12/projeto_v0/Views/Atividade/Edit.cshtml
@model projeto_v0.Models.Atividade

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar atividade</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atividade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resumo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.resumo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.resumo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_ini, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_ini, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_ini, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_fim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_fim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_fim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.carga_horaria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.carga_horaria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carga_horaria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cod_responsavel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cod_responsavel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cod_responsavel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.local, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.local, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.local, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cod_tipo_ativ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cod_tipo_ativ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cod_tipo_ativ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Savar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

projeto_v12/projeto_v0/Views/Atividade/Index.cshtml
@model IEnumerable<projeto_v0.Models.Atividade>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Lista de Atividades</h3>

<p>
    @Html.ActionLink("Adicionar nova Atividade", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Código
        </th>
        <th>
            Nome da Atividade
        </th>
        <th>
            Resumo
        </th>
        <th>
           Data de Inicio
        </th>
        <th>
            Data de Fim
        </th>
        <th>
            Carga Horária
        </th>
        <th>
            Código do Responsável
        </th>
        <th>
            Ano do Curso
        </th>
        <th>
            Local do Curso
        </th>
        <th>
            Código do Tipo de Atividade
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.resumo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.data_ini)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.data_fim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.carga_horaria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cod_responsavel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ano)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.local)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cod_tipo_ativ)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
            @Html.ActionLink("Matricular Alunos", "CreatePorArquivo", "Certificado", new { id = item.id }, null) |
            @Html.ActionLink("Alunos", "Detalhes", new { id = item.id })|
            @Html.ActionLink("Concluir Atividade", "ConcluirAtividade", "Certificado", new { id = item.id }, null) |
            @Html.ActionLink("Excluir", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>