projeto_v12/projeto_v0/Controllers/AssinaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projeto_v0.Models;

namespace projeto_v0.Controllers
{
    public class AssinaturaController : Controller
    {
        AssinaturaDAO assinaturaDAO = new AssinaturaDAO();
        public static List<Assinatura> listaAssinatura = new List<Assinatura>();
        // GET: Assinatura
        public ActionResult Index()
        { 
            //USARÁ???
            listaAssinatura = assinaturaDAO.List();
            return View(listaAssinatura);
            //var assinaturas = from b in listaAssinatura
                         //orderby b.id
                         //select b;
            //return View(assinaturas);
        }

        // GET: Assinatura/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Assinatura/Create
        public ActionResult Create()
        {
            return View();
        }
        //DECIDIR QUAL UTILIZAR
        /*
        // POST: Banda/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Assinatura assinatura = new Assinatura();
                assinatura.id = listaAssinatura.Count;
                assinatura.nome = collection["nome"];
                assinatura.caminho = collection["caminho"];
                assinatura.cargo = collection["cargo"];

                listaAssinatura.Add(assinatura);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        */

        // POST: Assinatura/Create
        [HttpPost]
        public ActionResult Create(Assinatura assinatura)
        {
            try
            {
                // TODO: Add insert logic here

                listaAssinatura.Add(assinatura);
                assinaturaDAO.Create(assinatura);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Assinatura registrada com sucesso!", "Sucesso");
            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao registrar assinatura!", "Erro");

            }
        }

        // GET: Assinatura/Edit/5
        public ActionResult Edit(int id)
        {

            var assinatura = listaAssinatura.Single(p => p.id == id);

            return View(assinatura);
        }

        // POST: Assinatura/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var assinatura = listaAssinatura.Single(p => p.id == id);
                if (TryUpdateModel(assinatura))
                {
                    assinaturaDAO.Edit(assinatura);
                    //return RedirectToAction("Index");
                    return RedirectToAction("Index").Mensagem("Assinatura alterada com sucesso!", "Sucesso");

                }
                return View(assinatura);

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao alterar Assinatura!", "Erro");

            }
        }

        // GET: Assinatura/Delete/5
        public ActionResult Delete(int id)
        {
            var assinatura = listaAssinatura.Single(p => p.id == id);
            return View(assinatura);
        }

        // POST: Assinatura/Delete/5
        [HttpPost]
        public ActionResult Delete(Assinatura assinatura)
        {
            try
            {
                listaAssinatura.Remove(assinatura);
                assinaturaDAO.Delete(assinatura);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Assinatura excluído com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao excluir Assinatura!", "Erro");

            }
        }
        /*
        public static List<Assinatura> listaAssinatura = new List<Assinatura>{
           new Assinatura{
              id = 1,
              nome = "Anderson",
              caminho="/c",
              cargo="coodenador"
           },
            new Assinatura{
              id = 2,
              nome = "Anderson",
              caminho="/c",
              cargo="diretor",
           },           
        };*/
    }
}

projeto_v12/projeto_v0/Controllers/AtividadeController.cs
using projeto_v0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace projeto_v0.Controllers
{
    public class AtividadeController : Controller    {

        AtividadeDAO atividadeDAO = new AtividadeDAO();
        public static List<Atividade> listaAtividade = new List<Atividade>();
        // GET: Atividade
        public ActionResult Index()
        {
            listaAtividade = atividadeDAO.List();
            return View(listaAtividade);
            
        }

        // GET: Atividade/Create
        public ActionResult Create()
        {
            return View();            
        }
        // POST: Atividade/Create
        [HttpPost]
        public ActionResult Create(Atividade atividade)
        {
            try
            {

                listaAtividade.Add(atividade);
                atividadeDAO.Create(atividade);
                //return RedirectToAction("Index");
                if (atividade == null) throw new Exception();
                return RedirectToAction("Index").Mensagem("Atividade registrada com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();                
                return View().Mensagem("Erro ao registrar Atividade!", "Erro");

            }
        }

        // GET: Atividade/Edit/5
        public ActionResult Edit(int id)
        {
            var atividade = listaAtividade.Single(p => p.id == id);

            return View(atividade);
        }

        // POST: Atividade/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var atividade = listaAtividade.Single(p => p.id == id);
                if (TryUpdateModel(atividade))
                {
                    atividadeDAO.Edit(atividade);
                    return RedirectToAction("Index");

                }
                //return View(atividade);
                return View().Mensagem("Atividade alterada com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao alterar atividade!", "Erro");
            }
        }

        // GET: Atividade/Delete/5
        public ActionResult Delete(int id)
        {
            Console.WriteLine("Usuario: " + id);
            var atividade = listaAtividade.Single(p => p.id == id);
            return View(atividade);
        }

        // POST: Atividade/Delete/5
        [HttpPost]
        //        public ActionResult Delete(int id, FormCollection collection)
        public ActionResult Delete(Atividade atividade)
        {
            try
            {
                listaAtividade.Remove(atividade);
                atividadeDAO.Delete(atividade);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Atividade excluído com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao excluir atividade!", "Erro");
            }
        }
        public ActionResult Detalhes(int id)
        {
            ViewBag.id=id;
            return View();
        }
    }
}

projeto_v12/projeto_v0/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projeto_v0.Models;

namespace projeto_v0.Controllers
{
    public class TemplateController : Controller
    {
        TemplateDAO TemplateDAO = new TemplateDAO();
        public static List<Template> listaTemplate = new List<Template>();
        // GET: Template
        public ActionResult Index()
        {
            //USARÁ???
            listaTemplate = TemplateDAO.List();
            return View(listaTemplate);
            //var Templates = from b in listaTemplate
                            //orderby b.id
                            //select b;
            //return View(Templates);
        }

        // GET: Template/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Template/Create
        public ActionResult Create()
        {
            return View();
        }
        //DECIDIR QUAL UTILIZAR
        /*
        // POST: Banda/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Template Template = new Template();
                Template.id = listaTemplate.Count;
                Template.nome = collection["nome"];
                Template.caminho = collection["caminho"];
                Template.cargo = collection["cargo"];

                listaTemplate.Add(Template);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        */

        // POST: Template/Create
        [HttpPost]
        public ActionResult Create(Template Template)
        {
            try
            {
                // TODO: Add insert logic here

                listaTemplate.Add(Template);
                TemplateDAO.Create(Template);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Template registrado com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao registrar template!", "Erro");
            }
        }

        // GET: Template/Edit/5
        public ActionResult Edit(int id)
        {

            var Template = listaTemplate.Single(p => p.id == id);

            return View(Template);
        }

        // POST: Template/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var Template = listaTemplate.Single(p => p.id == id);
                if (TryUpdateModel(Template))
                {
                    TemplateDAO.Edit(Template);
                    //return RedirectToAction("Index");
                    return RedirectToAction("Index").Mensagem("Template alterado com sucesso!", "Sucesso");

                }
                return View(Template);

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao alterar template!", "Erro");

            }
        }

        // GET: Template/Delete/5
        public ActionResult Delete(int id)
        {
            var Template = listaTemplate.Single(p => p.id == id);
            return View(Template);
        }

        // POST: Template/Delete/5
        [HttpPost]
        public ActionResult Delete(Template Template)
        {
            try
            {
                listaTemplate.Remove(Template);
                TemplateDAO.Delete(Template);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Template excluído com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao excluir template!", "Erro");

            }
        }
        /*
        public static List<Template> listaTemplate = new List<Template>{
           new Template{
              id = 1,
              nome = "Anderson",
              caminho="/c",
              cargo="coodenador"
           },
            new Template{
              id = 2,
              nome = "Anderson",
              caminho="/c",
              cargo="diretor",
           },           
        };*/
    }
}

projeto_v12/projeto_v0/Controllers/UsuarioController.cs
using projeto_v0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projeto_v0.Controllers
{  
    public class UsuarioController : Controller
    {

        UsuarioDAO usuarioDAO = new UsuarioDAO();
        public static List<Usuario> listaUsuario = new List<Usuario>();       

        // GET: Usuario
        public ActionResult Index()
        {
            listaUsuario = usuarioDAO.List();
            return View(listaUsuario);
            
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }
        //DECIDIR QUAL UTILIZAR
        /*
        // POST: Banda/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Usuario usuario = new Usuario();
                usuario.id = listaUsuario.Count;
                usuario.nome = collection["nome"];
                usuario.usuario = collection["usuario"];
                usuario.email = collection["email"];
                usuario.senha = collection["senha"];
                
                listaUsuario.Add(usuario);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
    */
        // POST: Usuario/Create
        [HttpPost]
        public ActionResult Create(Usuario usuario)
        {
            try
            {
                listaUsuario.Add(usuario);                
                usuarioDAO.Create(usuario);

                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Usuário registrado com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao registrar usuário!", "Erro");
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            var usuario = listaUsuario.Single(p => p.id == id);

            return View(usuario);
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var usuario = listaUsuario.Single(p => p.id == id);
                if (TryUpdateModel(usuario))
                {
                    usuarioDAO.Edit(usuario);
                    //return RedirectToAction("Index");
                    return RedirectToAction("Index").Mensagem("Usuário alterado com sucesso!", "Sucesso");
                }
                return View(usuario);
            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao alterar usuário!", "Erro");
            }
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int id)
        {
            var usuario = listaUsuario.Single(p => p.id == id);
            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        // public ActionResult Delete(int id, FormCollection collection)
        public ActionResult Delete(Usuario usuario)
        {
            try
            {
                listaUsuario.Remove(usuario);
                usuarioDAO.Delete(usuario);
                //return RedirectToAction("Index");
                return RedirectToAction("Index").Mensagem("Usuário excluído com sucesso!", "Sucesso");

            }
            catch
            {
                //return View();
                return View().Mensagem("Erro ao excluir usuário!", "Erro");
            }
        }
    }
}

projeto_v12/projeto_v0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>     
    

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body id="body-container">    
        @Html.Partial("_navBar")
    
    <div class="container body-content">
        @RenderBody()
        <hr/>    
        <footer>
            <p>&copy; @DateTime.Now.Year - Certifique-se &copy; Todos os direitos reservado.</p>
        </footer>
    </div>   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @{Html.RenderPartial("~/Views/Shared/_Mensagem.cshtml");} 

  
</body>
</html>

projeto_v12/projeto_v0/Views/Shared/_Mensagem.cshtml
<!--
    Html e Script para gerar Mensagens Modal com uso do Bootstrap em sua Aplicação

      * Carrega Mensagem quando chamada como extensão de sua view
      * Funcão MensagemvConfirma - Gera Modal com mensagem de confimação

    Visite http://www.codigoexpresso.com.br
-->
@{
    var Mensagem = "";
    var Titulo = "";
    if (TempData["Mensagem"] != null)
    {
        Mensagem = TempData["Mensagem"].ToString();
        Titulo = TempData["Titulo"].ToString();
    }
}

@if (Mensagem != "")
{
    <!--Formulario principal para Display de Mensagens /Views/shared/_Mensagem.cshtml-->
    <div id="ModalMensagem" class="modal fade" style="margin: 20% 0 0 35%; width:30%; height:30%;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="margin:0px">                    
                    <h4 class="modal-title" id="titulo" style="margin-left: 40%; margin-top:0px;">@Titulo</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12 text-center" style="vertical-align:center">
                            @Html.Raw(Mensagem)
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm" style="margin:20% 0 0 25%" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
    $(document).ready(function () {
        $("#ModalMensagem").modal('show');
        });
    </script>

    <!--Fim Formulario principal para Display de Mensagens -->
}

<!--Formulario principal para Display de Mensagem de Confirmação /Views/shared/_Mensagem.cshtml-->

<div id="ModalConfirma" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content" id="BodyConfirma">
            <!--Conteudo Dinamico-->
        </div>
    </div>
</div>

<script type="text/javascript">  

    // Funcao para Carregar Mensagem de confirmação, se teclar no botão SIM desvia para o link informado
    function MensagemConfirma(Titulo, Mensagem, Link)
    {
        var data ='<div class="modal-header">'+
                  '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>'+
                  '<h4 class="modal-title">'+Titulo+'</h4>'+
                  '</div>'+
                  '<div class="modal-body">'+
                  '<div class="row">'+
                  '<div class="col-md-12 text-center">'+Mensagem+'</div>'+
                  '</div>'+
                  '</div>'+
                  '<div class="modal-footer">'+
                  '<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Não</button>' +
                  '<a href="'+Link+'" class="btn btn-sm btn-default">Sim</a>'+
                  '</div>';
        $('#BodyConfirma').html(data);
        $("#ModalConfirma").modal('show');
    }

    // Funcao para Carregar Mensagem
    function Mensagem(Titulo, Mensagem) {
        var data = '<div class="modal-header">' +
                  '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                  '<h4 class="modal-title">' + Titulo + '</h4>' +
                  '</div>' +
                  '<div class="modal-body">' +
                  '<div class="row">' +
                  '<div class="col-md-12 text-center">' + Mensagem + '</div>' +
                  '</div>' +
                  '</div>' +
                  '<div class="modal-footer">' +
                  '<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">OK</button>' +
                  '</div>';
        $('#BodyConfirma').html(data);
        $("#ModalConfirma").modal('show');
    }

</script>

<script>
      var titulo = $('#titulo').text();
      console.log(titulo);

      var msg = document.getElementById("ModalMensagem");

      if (titulo == "Sucesso") {
          msg.style.backgroundColor = "darkseagreen";
      }

      else if (titulo == "Atenção") {

          msg.style.backgroundColor = "yellow";
      }

      else if (titulo == "Erro") {

          msg.style.backgroundColor = "red";
      }
</script>



<!--Fim Formulario principal para Display de Mensagem de Confirmação -->

projeto_v12/projeto_v0/Views/Shared/_navBar.cshtml
<nav class="navbar">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li><img src="~/img/logotipo.png" style="height:60px;width:110px; margin-top:0"/></li>                

                <li class="dropdown">
                    <span class="glyphicon glyphicon-home"></span>
                    @Html.ActionLink("Home", "Index", "Home", null, null)
                </li>

                <li class="dropdown">
                    <span class="glyphicon glyphicon-user"></span>
                     @Html.ActionLink("Gerenciar Usuários", "Index", "Usuario", null, null)                   
                </li>

                <li class="dropdown">
                    <span class="glyphicon glyphicon-tasks"></span>
                    @Html.ActionLink("Gerenciar Atividades", "Index", "Atividade", null, null)
                </li>

                <li class="dropdown">
                    <span class="glyphicon glyphicon-pencil"></span>
                    @Html.ActionLink("Gerenciar Matrículas", "Index", "Participante", null, null)
                </li>               

                <li class="dropdown">
                    <span class="glyphicon glyphicon-education"></span>
                    @Html.ActionLink("Gerenciar certificados", "Index", "Certificado", null, null)
                </li>               

                <li class="dropdown">
                    <span class="glyphicon glyphicon-th-large"></span>
                    @Html.ActionLink("Templates", "Index", "Template", null, null)                
                </li>  
                
                <li class="dropdown">
                    <span class="glyphicon glyphicon-edit"></span>
                    @Html.ActionLink("Gerenciar assinaturas", "Index", "Assinatura", null, null)
                </li>
            </ul>           
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>